services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tracker
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - '5432:5432'
    restart: always

volumes:
  postgres-data: