services:
  backend:
    build:
      ./backend
    ports:
      - '8888:8888'
    restart: always
    depends_on:
      - postgres

  frontend:
    build:
      ./frontend
    ports:
      - '3333:3333'
    restart: always
    volumes:
      - /app/node_modules
      - ./frontend:/app

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tracker
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    # don't forget to remove database ports before submitting
    ports:
      - '5432:5432'
    restart: always

volumes:
  postgres-data: